import type { Metadata } from 'next';
import '../globals.css';
import ReactQueryProvider from '@/providers/react-query-provider';
import { ThemeProvider } from '@/providers/theme-provider';
import HeaderNav from '@/components/layout/header-nav';
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface IProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default async function LocaleLayout({
  children,
  params: { locale },
}: IProps) {
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      dir={`${locale == 'ar' ? 'rtl' : 'ltr'}`}
      suppressHydrationWarning
    >
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NextIntlClientProvider messages={messages}>
              <HeaderNav />
              {children}
            </NextIntlClientProvider>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
